//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturers
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LecID { get; set; }
    
        public virtual Lectures Lectures { get; set; }
        public virtual Users Users { get; set; }
    }
}
