//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LecID { get; set; }
        public Nullable<int> DisC { get; set; }
        public Nullable<int> Midterm { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Resist { get; set; }
        public Nullable<double> Grade { get; set; }
    
        public virtual Lectures Lectures { get; set; }
        public virtual Users Users { get; set; }
    }
}
